<?php

declare(strict_types=1);

namespace Toporia\Framework\Routing;

use Toporia\Framework\Routing\Contracts\RouteCacheInterface;

/**
 * Route Cache Implementation
 *
 * File-based route caching for maximum performance.
 *
 * Performance Optimizations:
 * - var_export() for faster serialization than serialize()
 * - Opcache compatible (PHP file caching)
 * - Zero overhead on cached routes (include returns array)
 * - Atomic file writing (rename for safety)
 *
 * Cache Format:
 * - PHP file returning array (opcache friendly)
 * - Pre-compiled regex patterns
 * - Flattened route structure for O(1) lookup
 *
 * Architecture:
 * - Single Responsibility: File-based caching
 * - Open/Closed: Can extend for Redis/Memory cache
 * - Dependency Inversion: Implements interface
 *
 * @package Toporia\Framework\Routing
 */
final class RouteCache implements RouteCacheInterface
{
    /**
     * @var string Cache file path
     */
    private string $cachePath;

    /**
     * @param string $cachePath Path to cache directory
     */
    public function __construct(string $cachePath)
    {
        $this->cachePath = rtrim($cachePath, '/') . '/routes.php';
    }

    /**
     * {@inheritdoc}
     */
    public function isCached(): bool
    {
        return file_exists($this->cachePath);
    }

    /**
     * {@inheritdoc}
     */
    public function get(): ?array
    {
        if (!$this->isCached()) {
            return null;
        }

        try {
            // Include returns array - opcache friendly!
            $routes = include $this->cachePath;

            if (!is_array($routes)) {
                return null;
            }

            return $routes;
        } catch (\Throwable $e) {
            return null;
        }
    }

    /**
     * {@inheritdoc}
     */
    public function put(array $routes): bool
    {
        try {
            // Ensure cache directory exists
            $dir = dirname($this->cachePath);
            if (!is_dir($dir)) {
                mkdir($dir, 0755, true);
            }

            // Generate PHP file content
            $content = $this->generateCacheFile($routes);

            // Atomic write: write to temp file then rename
            $tempPath = $this->cachePath . '.tmp';
            file_put_contents($tempPath, $content, LOCK_EX);

            // Atomic rename (avoids partial reads)
            rename($tempPath, $this->cachePath);

            // Clear opcache for this file
            if (function_exists('opcache_invalidate')) {
                opcache_invalidate($this->cachePath, true);
            }

            return true;
        } catch (\Throwable $e) {
            return false;
        }
    }

    /**
     * {@inheritdoc}
     */
    public function clear(): bool
    {
        if (!$this->isCached()) {
            return true;
        }

        try {
            unlink($this->cachePath);

            // Clear opcache
            if (function_exists('opcache_invalidate')) {
                opcache_invalidate($this->cachePath, true);
            }

            return true;
        } catch (\Throwable $e) {
            return false;
        }
    }

    /**
     * {@inheritdoc}
     */
    public function getCachePath(): string
    {
        return $this->cachePath;
    }

    /**
     * Generate cache file content.
     *
     * Performance: var_export is faster than serialize and opcache-friendly.
     *
     * @param array $routes Routes data
     * @return string PHP file content
     */
    private function generateCacheFile(array $routes): string
    {
        $export = var_export($routes, true);

        return <<<PHP
<?php

/**
 * Cached Routes
 *
 * This file is auto-generated by route:cache command.
 * Do not edit manually!
 *
 * Regenerate with: php console route:cache
 * Clear with: php console route:clear
 */

return {$export};

PHP;
    }
}
